[workspace]
authors = ["udit-asopa <udit.asopa@gmail.com>"]
channels = ["conda-forge"]
name = "british_airways_lounge"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.3.1,<3"
numpy = ">=2.3.2,<3"
pathlib = ">=1.0.1,<2"
jupyter = ">=1.1.1,<2"
jupyterlab = ">=4.4.5,<5"
bash_kernel = ">=0.10.0,<0.11"
ipywidgets = ">=8.1.7,<9"
matplotlib = ">=3.10.3,<4"
seaborn = ">=0.13.2,<0.14"
scikit-learn = ">=1.7.1,<2"
scipy = ">=1.16.0,<2"
joblib = ">=1.5.1,<2"
